// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgt6W7GH2TOh8iwXWTJ_Gn93_Br9hnV0E',
    appId: '1:67898588546:android:06ba9bb66e15af8b67a39b',
    messagingSenderId: '67898588546',
    projectId: 'flutter-tour-bus-new',
    storageBucket: 'flutter-tour-bus-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzrnzJxCwpNKs7Y-aaV-HO-22pmgTkVeA',
    appId: '1:67898588546:ios:9ea1c94ff6c20c3c67a39b',
    messagingSenderId: '67898588546',
    projectId: 'flutter-tour-bus-new',
    storageBucket: 'flutter-tour-bus-new.appspot.com',
    iosClientId: '67898588546-4hnl46q06jgolo33h54gomf3i8hiiku1.apps.googleusercontent.com',
    iosBundleId: 'com.chijia.flutterTourBusNew',
  );
}
